### ISSUE TITLE
Field editor deletes Scheduling value.

### ISSUE THREAD

**Issue by slevkelevra** [sitecorepm/SitecoreShellWax#2]
Hi Paul,

i noticed an error in the SitecoreShellWax module. The error occurs when saving tasks.

The problem can be reproduced easily.

0. Install SitecoreShellWax
1. Create Task
2. Use Field Editor to define Scheduling
3. Save Item
4. Click on any other item ...

Now the Save As dialog appears again, although no further changes were made. 
When I confirm the dialog with "Yes", the definition of the Schedule Field is being reset.

The error also occurs when I save the task twice in a row.

If you are aware of the problem? Is there already a solution?

I use:
Sitecore 7.2 (rev. 140526) 
SitecoreShellWax 1.3

Many greetings

**Comment by slevkelevra** [comment]
Thank you for your effort. The bugfix has solved the problem.

**Comment by sitecorepm** [comment]
Great! I'm glad that resolved it. Thanks for your investigation and submission of the issue!
